import { ChatGroq } from "@langchain/groq";
import { HumanMessage, SystemMessage } from "@langchain/core/messages";
import dotenv from "dotenv";
import { CoderOutputSchema } from "../schemas.js";

dotenv.config();

const model = new ChatGroq({
  apiKey: process.env.GROQ_API_KEY,
  modelName: "llama-3.3-70b-versatile",
});

/**
 * Coder node: Generates code for each file defined by the architect.
 */
export async function coder(state) {
  console.log("--- CODER ---");
  const { plan, architecture } = state;
  const files = {};
  const allFileNames = architecture.map((explaination) => explaination.filename);
  for (const explaination of architecture) {
    const importantNotes = Object.entries(files).reduce((acc, [key, value]) => {
      return acc + `${key}: ${value.importantNotes}` + "\n";
    }, "");
    const filename = explaination.filename;
    const content = explaination.content;
    console.log(`Generating code for ${filename}...`);
    const systemPrompt = `You are an expert web developer. Based on the following plan and explanation, generate the code for the file: ${filename}, 
    follow the following instructions from architect:${content}.
    The other files that will be generated by other agents are:${allFileNames}.
Plan:
${plan}
Important NOtes from other file developers:
${importantNotes}
Strictly follow json response structure, important notes should contain notes that are needed to be considered while generating other linked files. Eg: if html file has class names, 
note must include the id names used in html file and instructions that are needed for that file generation.
Example:
   Output: {code:"code here",importantNotes:"any important notes for the file"}
   Strictly respond with json object only - !CRITICAL.`;

    const structuredModel = model.withStructuredOutput(CoderOutputSchema);
    const response = await structuredModel.invoke([
      new SystemMessage(systemPrompt),
      new HumanMessage(`Generate code for ${filename}`),
    ]);

    files[filename] = response;
  }

  return {
    files: files,
    status: "Code generated for all files.",
  };
}
